Rpath is not allowed in Fedora
This patch suppresses the following error message:

```
+ /usr/lib/rpm/check-rpaths
*******************************************************************************
*
* WARNING: 'check-rpaths' detected a broken RPATH OR RUNPATH and will cause
*          'rpmbuild' to fail. To ignore these errors, you can set the
*          '$QA_RPATHS' environment variable which is a bitmask allowing the
*          values below. The current value of QA_RPATHS is 0x0000.
*
*    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
*               issue but are introducing redundant searchpaths without
*               providing a benefit. They can also cause errors in multilib
*               environments.
*    0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
*               nor relative filenames and can therefore be a SECURITY risk
*    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
*               SECURITY risk
*    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
*               RPATHs; this is just a minor issue but usually unwanted
*    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
*               and they cause unneeded work while loading libraries
*    0x0020 ... an RPATH references '..' of an absolute path; this will break
*               the functionality when the path before '..' is a symlink
*
*
* Examples:
* - to ignore standard and empty RPATHs, execute 'rpmbuild' like
*   $ QA_RPATHS=$(( 0x0001|0x0010 )) rpmbuild my-package.src.rpm
* - to check existing files, set $RPM_BUILD_ROOT and execute check-rpaths like
*   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
*
*******************************************************************************
ERROR   0002: file '/usr/bin/erigon-txpool' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon-state' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon-sentry' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon-rpcdaemon' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon-integration' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon-hack' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
ERROR   0002: file '/usr/bin/erigon' contains an invalid runpath '/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64' in [$ORIGIN:$ORIGIN/../lib:/builddir/build/BUILD/erigon-2.56.0/go/pkg/mod/github.com/erigontech/silkworm-go@v0.10.0/lib/linux_x64]
error: Bad exit status from /var/tmp/rpm-tmp.a49HxQ (%install)
    Bad exit status from /var/tmp/rpm-tmp.a49HxQ (%install)
```

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>